### PR TITLE
Add LangGraph fact-checking feedback loop example for Bedrock

### PR DESCRIPTION
**Pull request by eercanayar**
*Issue #, if available:*

*Description of changes:*
Introduces a notebook demonstrating a fact-checking feedback loop for AI-generated summaries with LangGraph on Amazon Bedrock. This will unlock numerous ongoing customer engagements that require this approach.

The notebook includes:
- Fact-checking logic walk-through
- Fact-checking feedback loop implementation with LangGraph
- Integration with Amazon Bedrock models
- Automated summary verification and self-correction
- End-to-end invocation and testing

This enhances workshop content with an advanced use case for improving the accuracy and reliability of AI-generated content.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by eercanayar** [comment]
@rsgrewal-aws can you review this?

**Review by rsgrewal-aws — CHANGES_REQUESTED** [review]
please move this under the agents_and_functions and then under open source . we are NOT allowing any top level folders on this repo

**Comment by eercanayar** [comment]
Re-organized files. Now the example is under `06_OpenSource_examples/05_OpenSource_agents`.
Ready to merge @rsgrewal-aws .

**Review by rsgrewal-aws — APPROVED** [review]
approved

**Pull request merged**
