### PR TITLE
Fix issues #71; #75; and centralize package dependencies

### PR DESCRIPTION
**Pull request by jld23**
*Issue #, if available:*

*Description of changes:*
Moved the dependencies for each notebook to the 00 setup notebook and changed the note in each notebook to run setup as a first step. 
This will simplify the maintanance as package versions change.
In the process of testing I ran into issues #71 and #75 so I fixed them also.

I don't have titan text access in my test account so I'm assuming it will work based on the other notebooks.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rsgrewal-aws** [comment]
Could you please update the Langchain to 0.0.309 and  update this PR with to the latest code -- the latest code has changes to all the files for lanchagin and to get around the claude issues
import warnings
warnings.filterwarnings('ignore')

as suggested by the Langchain developers

**Comment by jld23** [comment]
I bumped langchain to 0.0.309 and add at `setup` section to each readme (note agents in lab 7 doesn't have a readme).

I you need anything else before merging please let me know.

**Comment by lauerarnaud** [comment]
00_Intro
    bedrock_boto3_setup
    - You have this “PyPDF, for handling PDF file“ listed twice
    - “but for later notebooks in the workshop you'll also need to other packages.” it is missing a word, “access to other packages”?
    - Should we change to the latest AI21Labs Jurassic model to the latest model? “ai21.j2-mid-v1”

01_Generation
    00_generate_w_bedrock
    - Should we put a little warning icon in front of this “Before running this notebook, ensure you've run the Bedrock boto3 setup notebook notebook.”? (Since it is fairly important) - this is applicable across all the notebooks
    - Clear the outputs for this notebook (worth checking the other ones as well)
    - It is not one of your changes but should we replace the following text with “Check [documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) for Available text generation model Ids under Amazon Bedrock.” Instead - it will ease maintenance as the model IDs are going to change over time?

    Available text generation models under Amazon Bedrock have the following IDs:
    - `amazon.titan-tg1-large`
    - `ai21.j2-grande-instruct`
    - `ai21.j2-jumbo-instruct`
    - `anthropic.claude-instant-v1`
    - `anthropic.claude-v2`

    01_zero_shot_generation
    - It is not linked to your PR but there is a typo in one of the title “Useccase”, should be “Use case”.
    - Whilst we installed it in setup notebook, should we also mentioned In this notebook: “In this notebook, we'll use the Hugging Face Transformers library which we installed in bedrock_boto3_setup for counting the number of tokens in an input prompt.?

02_Summarization
    02.long-text-summarization-titan
    - Whilst we installed it in setup notebook, should we also mentioned In this notebook: “In this notebook, we'll use the Hugging Face Transformers library which we installed in bedrock_boto3_setup for counting the number of tokens in an input prompt.?
    - > ⏰ **Note:** Depending on your number of documents, Bedrock request rate quota, and configured retry settings - this chain may take some time to run: >> remove “:” at the end or replace with “.”.

03_QuestionAnswering
    01_qa_w_rag_claude
    - It is not linked to your PR but there is a typo in one of the title “Useccase”, should be “Use case”.
    - It is not one of your changes but should we replace the following text with “Check [documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) for Available text generation model Ids under Amazon Bedrock.” Instead?

    Available text generation models under Amazon Bedrock have the following IDs:
    - - `amazon.titan-tg1-large`
    - - `ai21.j2-grande-instruct`
    - - `ai21.j2-jumbo-instruct`
    - - `anthropic.claude-instant-v1`
    - - `anthropic.claude-v2`

    00_Chatbot_Claude
    - Not working getting error.

    /opt/conda/lib/python3.10/site-packages/langchain/llms/bedrock.py:46: UserWarning: Error: Prompt must alternate between '
    Human:' and '
    Assistant:'. Received 

    02_qa_w_rag_claude_pinecone
    - It is not linked to your PR but there is a typo in one of the title “Useccase”, should be “Use case”.
    - The Implementation section still reference FAISS.
    - Cell 10 is not working. It is missing index_name
    - Cell 15 is not working. There is no “data” define hence the cell is failing.

    Readme.md
    - It is missing the 3rd notebook with Pinecone listed.

04_Chatbot
    00_Chatbot_AI21
    - Why does the chatbot responds to “hello” with the following answer “Amazon SageMaker is a fully managed service to prepare data and build, train, and deploy”

06_CodeGeneration
    02_code_interpret_w_langchain
    - It is not one of your changes but should we replace the following text with “Check [documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) for Available text generation model Ids under Amazon Bedrock.” Instead?

    Available text generation models under Amazon Bedrock have the following IDs:
    - - `amazon.titan-tg1-large`
    - - `ai21.j2-grande-instruct`
    - - `ai21.j2-jumbo-instruct`
    - - `anthropic.claude-instant-v1`
    - - `anthropic.claude-v2`

    03_code_translate_w_langchain
    - It is not one of your changes but should we replace the following text with “Check [documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) for Available text generation model Ids under Amazon Bedrock.” Instead?

    Available text generation models under Amazon Bedrock have the following IDs:
    - - `amazon.titan-tg1-large`
    - - `ai21.j2-grande-instruct`
    - - `ai21.j2-jumbo-instruct`
    - - `anthropic.claude-instant-v1`
    - - `anthropic.claude-v2`

    06_CodeGeneration/README.md
    - It is missing the other diagrams

07_Agents
    00_LLM_Claude_Agent_Tools
    - Cell 6 is failing
    ValidationError: 1 validation error for SerpAPIWrapper
    __root__
    Did not find serpapi_api_key, please add an environment variable `SERPAPI_API_KEY` which contains it, or pass  `serpapi_api_key` as a named parameter. (type=value_error)

    01_LLM_Claude_Agent_Stock_Analysis
    - Cell 16 getting Claude issue.

    /opt/conda/lib/python3.10/site-packages/langchain/llms/bedrock.py:46: UserWarning: Error: Prompt must alternate between '
    Human:' and '
    Assistant:'. Received 

08_EntityExtraction
    entity_extraction
    - It is not one of your changes but should we replace the following text with “Check [documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids-arns.html) for Available text generation model Ids under Amazon Bedrock.” Instead?

    Available text generation models under Amazon Bedrock have the following IDs:
    - - `amazon.titan-tg1-large`
    - - `ai21.j2-grande-instruct`
    - - `ai21.j2-jumbo-instruct`
    - - `anthropic.claude-instant-v1`
    - - `anthropic.claude-v2`

    - Typo “In addition, LLM entity extraction can be used to help you assemble a dataset to later creat a customised solution for your use case, such as Amazon Comprehend custom entity recognition.” >> “create”

**Review by lauerarnaud — APPROVED** [review]

**Comment by lauerarnaud** [comment]
Thanks @jld23 retested all files and it looks good. @tchattha over to you for merge.

**Comment by rsgrewal-aws** [comment]
changes look good

**Pull request closed without merging**
